### ISSUE TITLE
Distinguish null and non-exist fields

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_json#30]
In tink_web I would like to create an API to patch data in database, where fields provided will be updated (even the value is null). So there is a need to distinguish a field of value `null` and a field that doesn't exist at all.

When this is supported in tink_json, we may add some meta in tink_web to toggle the behavior...

Related: #6

**Comment by back2dos** [comment]
This is probably going to be rather fragile, because Haxe in itself does not provide for a proper way to find out if a field is set or not. There is reflection, yes, but that is slow, tends to inflate build size and isn't closure advanced mode compatible.

I would suggest a more explicit syntax, with a `@:genericBuild class Patch<T> {}` that would turn `Patch<{ x:X, y:Y }>` into `{ ?x:FieldPatch<X>, ?y:FieldPatch<Y> }` with this:

```haxe
enum FieldPatch<T> {
  Set(value:T):FieldPatch<T>;
  Add<X:Float>(by:X):FieldPatch<X>;
  ListUpdate<X>(add:Array<X>, remove:Array<X>):FieldPatch<Array<X>>;
  //... etc.
}
```

It's not unlike the update type proposed for tink_sql.

**Comment by kevinresol** [comment]
While this may be a solution if the client is also written in Haxe. I am afraid it is not the case if the client is written in other languages, which expects a simple JSON api, where updates are only performed when the field exists.

Could tink_json produce an abstract instead of a anonymous object, like this:

```haxe
var obj:Parsed<MyObj> = tink.Json.parse(string);

@:genericBuild(/* a macro to produce the abstract below */)
class Parsed<T> {}

@:forward
abstract Parsed0(ParsedBase0) {
  @:to public function toObj():MyObj;
}

class ParsedBase0 {
  public var data:MyObj;
  public var exists: {
    field1:Bool, // fill these values at parse-time, so no reflection needed
    field2:Bool,
    // ...
  }
}

```

**Comment by back2dos** [comment]
This is now handled by #34.
