### ISSUE TITLE
Dynamic parser references and type parameters

### ISSUE THREAD

**Issue by olichose123** [haxetink/tink_json#82]
While I understand that the creation of a parser or writer uses macros to detect the type and structure from the passed in type parameter, it makes passing around parser instances a bit of a pain. While it's not possible to build a macro from a type parameter T, it unfortunately refuses Dynamic in function arguments. so the following method is impossible:
`function load<T>(path:String, parser:tink.json.Parser<T>):T`
An alternative I found is to use an anonymous object with the signature `{function tryParse(source:String):Outcome<T, Error>;}`, but I was wondering if it is optimal. 
The library could either support some kind of LazyParser<T> that generates a parser at runtime to prevent the passing around of parsers, or more simply declare a typedef DynamicParser representing a parser of any type. Would this be more optimal? Is the concept of a generic load method so non-robust that I'm spending too much time on this?

Thanks for your output. Been using haxe for some time, always ignored tink_* libraries, but now that I'm getting into them, god they bring so many interesting concepts to the table.

**Comment by back2dos** [comment]
> An alternative I found is to use an anonymous object with the signature `{function tryParse(source:String):Outcome<T, Error>;}`, but I was wondering if it is optimal.

Yes, that sounds quite reasonable, although I'd personally drop the object.

```haxe
function load<T>(path:String, parse:String->T):T
// or perhaps
function load<T>(path:String, tryParse:String->Outcome<T, Error>):Outcome<T, Error>
```

And depending on your preference, pass the corresponding method.

> The library could either support some kind of LazyParser that generates a parser at runtime

Generating the parser at runtime is not possible, because the type information is long gone.

> Is the concept of a generic load method so non-robust that I'm spending too much time on this?

I can't speak to that. Without further context, I would define a generic load method as `function load(url:String):tink.core.Promise<String>` which is quite effortlessly composed with a parser via `load('http://foo.bar/glargh.json').next(new tink.json.Parser<Glargh>().tryParse)`.

If you do wish to have something with a signature closer to yours, you will need a macro:

```haxe
static macro function load(e) 
  return switch e {
    case macro ($url:$type): return macro @:pos(e.pos) doLoad($url, new tink.json.Parser<$type>().parse);
    default: haxe.macro.Context.error('expected (url:Type)');
  }
```

And thus `load(('http://foo.bar/glargh.json':Glargh))` will expand to `doLoad('http://foo.bar/glargh.json', new tink.json.Parser<Glargh>().parse)` (where `doLoad` is implemented as you see fit). Is that closer to what you want?

> Been using haxe for some time, always ignored tink_* libraries, but now that I'm getting into them, god they bring so many interesting concepts to the table.

Glad you like it. Have fun ;)

**Comment by olichose123** [comment]
Thanks a lot for your help!
